version: '3.3'

services:
  postgres:
    image: postgres:alpine
    command: postgres -N 300
    container_name: postgres
    ports:
      - 5433:5432
    restart: unless-stopped
    volumes:
      - ./data/dumps/demo.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./data/dumps:/dumps
    env_file:
      - ./data/env/database.dev.env

  backend:
    build: ./backend/
    image: tutor-backend
    container_name: backend
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./data/images:/images
      - ./data/load:/load
      - ./data/export:/export
    env_file:
      - ./data/env/backend.dev.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tutordb
