name: build

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: tests
      env:
        VARS_GITHUB_SHA: ${{ github.sha }}
        VARS_GITHUB_REF: ${{ github.ref }}
        VARS_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        echo "GITHUB_SHA: $GITHUB_SHA"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "rev-parse HEAD: $(git rev-parse HEAD)"
        echo "github.sha: $VARS_GITHUB_SHA"
        echo "github.ref: $VARS_GITHUB_REF"
        echo "github.event.pull_request.head.sha: $VARS_PR_HEAD_SHA"

        exit 1 # just stop
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
        project_id: quizzestutor
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
    - name: finish setting up terraform
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
      working-directory: infra
      run: |
        echo -n "$GOOGLE_APPLICATION_CREDENTIALS" | base64 -d > credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
        terraform init

    - name: build & push backend image
      env:
        DOCKER: docker
        DOCKER_BUILDKIT: 1
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
      working-directory: infra/backend-gce
      run: ./build-publish-image.sh
    - name: build & push frontend image
      env:
        DOCKER: docker
        DOCKER_BUILDKIT: 1
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
      working-directory: infra/frontend-gc
      run: ./build-publish-image.sh
    - name: build & push atlantis image
      env:
        DOCKER: docker
        DOCKER_BUILDKIT: 1
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
      working-directory: infra/atlantis-gcp
      run: ./build-publish-image.sh

    - name: cleanup gcp credentials for terraform
      run: rm infra/credentials.json
