name: build

on:
  push:
    branches:
    - master
    - develop
    - ops # TODO: remove
  pull_request:
    branches:
    - master
    - develop

jobs:
  build-backend:
    runs-on: ubuntu-latest

    # TODO: refactor for tighter integration with GitHub Actions
    steps:
    - uses: actions/checkout@v1
    - uses: google/cloud-sdk
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
        IMAGE: "backend-gce"
      run: |
        echo $GOOGLE_APPLICATION_CREDENTIALS | base64 -d > infra/credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/infra/credentials.json"

        pushd infra/$IMAGE
        ./build-publish-image.sh
        popd

        rm infra/credentials.json
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: google/cloud-sdk:alpine
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
        IMAGE: "frontend-gc"
      run: |
        echo $GOOGLE_APPLICATION_CREDENTIALS | base64 -d > infra/credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/infra/credentials.json"

        # frontend needs it
        apk add --no-cache terraform

        pushd infra/$IMAGE
        ./build-publish-image.sh
        popd

        rm infra/credentials.json
  build-atlantis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: google/cloud-sdk
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
        IMAGE: "atlantis-gcp"
      run: |
        echo $GOOGLE_APPLICATION_CREDENTIALS | base64 -d > infra/credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/infra/credentials.json"

        pushd infra/$IMAGE
        ./build-publish-image.sh
        popd

        rm infra/credentials.json
