name: build

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
        project_id: quizzestutor
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
    - name: finish setting up terraform
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
      working-directory: infra
      run: |
        echo -n "$GOOGLE_APPLICATION_CREDENTIALS" | base64 -d > credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
        terraform init

    - name: build & push backend image
      env:
        DOCKER: docker
        DOCKER_BUILDKIT: 1
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
      working-directory: infra/backend-gce
      run: ./build-publish-image.sh
    - name: build & push frontend image
      env:
        DOCKER: docker
        DOCKER_BUILDKIT: 1
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
      working-directory: infra/frontend-gc
      run: ./build-publish-image.sh
    - name: build & push atlantis image
      env:
        DOCKER: docker
        DOCKER_BUILDKIT: 1
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
      working-directory: infra/atlantis-gcp
      run: ./build-publish-image.sh

    - name: cleanup gcp credentials for terraform
      run: rm infra/credentials.json
