name: build

on:
  push:
    branches:
    - master
    - develop
    - ops # TODO: remove
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
        project_id: quizzestutor
    - uses: hashicorp/setup-terraform@v1

    - name: build & push backend image
      env:
        DOCKER: docker
      working-directory: infra/backend-gce
      run: ./build-publish-image.sh
    - name: build & push frontend image
      env:
        DOCKER: docker
      working-directory: infra/frontend-gc
      run: ./build-publish-image.sh
    - name: build & push image
      env:
        DOCKER: docker
      working-directory: infra/atlantis-gcp
      run: ./build-publish-image.sh

    - name: cleanup gcp credentials for terraform
      run: rm infra/credentials.json
