name: build

on:
  push:
    branches:
    - master
    - develop
    - ops # TODO: remove
  pull_request:
    branches:
    - master
    - develop

jobs:
  build-backend:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
        project_id: quizzestutor
    - name: build & push image
      env:
        DOCKER: docker
      working-directory: infra/backend-gce
      run: ./build-publish-image.sh
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
        project_id: quizzestutor
    - uses: hashicorp/setup-terraform@v1
    - name: setup gcp credentials for terraform
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
      run: echo $GOOGLE_APPLICATION_CREDENTIALS | base64 -d > infra/credentials.json
    - name: build & push image
      env:
        DOCKER: docker
      working-directory: infra/frontend-gc
      run: ./build-publish-image.sh
    - name: cleanup gcp credentials for terraform
      run: rm infra/credentials.json
  build-atlantis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY }}
        project_id: quizzestutor
    - name: build & push image
      env:
        DOCKER: docker
      working-directory: infra/atlantis-gcp
      run: ./build-publish-image.sh
